In [1]:
import numpy as np # 별명 사용

In [2]:
A= np.random.randn(3,2) #randn : 표준정규분포, random : 난수발생
A, A.shape, A.dtype

(array([[ 0.19801011,  1.79781081],
        [-1.38234631, -0.21522018],
        [-0.43589275, -0.7115123 ]]), (3, 2), dtype('float64'))

In [3]:
ls1=[1,2,4,4]
ls2=[33,25,74,78]
np.array(ls1), np.array([4,2,5,4,3]), np.array((4,2,5,4,3)) #벡터

(array([1, 2, 4, 4]), array([4, 2, 5, 4, 3]), array([4, 2, 5, 4, 3]))

In [4]:
ls1=[1,2,4,4]
ls2=[33,25,74,78]
vec_x=np.array((4,2,5,4,3))
mat_A=np.array([ls1,ls2])
mat_A # 행렬

array([[ 1,  2,  4,  4],
       [33, 25, 74, 78]])

In [5]:
ls1=[1,2,4,4]
ls2=[33,25,74,78]
vec_x=np.array((4,2,5,4,3))
mat_A=np.array([ls1,ls2])
print(vec_x.shape, vec_x.dtype)
print(mat_A.shape, mat_A.dtype)

(5,) int32
(2, 4) int32


In [6]:
ls1=[1,2,4,4]
ls2=[33,25,74,78]
np.asarray(ls1)

array([1, 2, 4, 4])

In [7]:
ls1=[1,2,4,4]
ls2=[33,25,74,78]
vec_y=np.asarray(ls2)
print(vec_y.shape, vec_y.dtype)

(4,) int32


In [8]:
ls1=[1,2,4,4]
ls2=[33,25,74,78]
vec_x=np.array((4,2,5,4,3))
mat_A=np.array([ls1,ls2])
print(vec_x.shape, vec_x.dtype)
print(mat_A.shape, mat_A.dtype)

vec_y=np.asarray(ls2)
mat_B=np.asarray(mat_A) 
print(vec_y.shape, vec_y.dtype)
print(mat_B.shape, mat_B.dtype)

print(id(ls2),id(vec_y)) #array가 아니면 새롭게 객체 생성
print(id(mat_A),id(mat_B)) # 이미 array이면, id가 공유되도록 

(5,) int32
(2, 4) int32
(4,) int32
(2, 4) int32
1900099437512 1900355977824
1900355980144 1900355980144


In [9]:
ls1=[1,2,4,4]
ls2=[33,25,74,78]
vec_x=np.arange(1,10,2)
vec_x # range와 동일하나 array로 생김

array([1, 3, 5, 7, 9])

In [10]:
np.zeros(2)

array([0., 0.])

In [11]:
np.zeros((4,5)) # 튜플 형식으로 지정

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
ls1=[1,2,4,4]
ls2=[33,25,74,78]
mat_A=np.array([ls1,ls2])

print(np.zeros_like(mat_A)) #mat_A와 크기가 같은 배열 만들어
print(mat_A)

[[0 0 0 0]
 [0 0 0 0]]
[[ 1  2  4  4]
 [33 25 74 78]]


In [13]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
ls1=[1,2,4,4]
ls2=[33,3,25,362,74,76,78,19]
vec_x=np.array(ls1, dtype=np.string_)
print(vec_x, vec_x.dtype) # type : 고정길이형 1

[b'1' b'2' b'4' b'4'] |S1


In [16]:
ls1=[1,2,4,4]
ls2=[33,3,25,362,74,76,78,19]
vec_x=np.array(ls1)
vec_x=vec_x.astype(np.float64)
print(vec_x, vec_x.dtype) # type : 64비트 실수

[1. 2. 4. 4.] float64


In [17]:
ls1=[1,2,4,4]
ls2=[33.3,25.362,74.76,78.19]
mat=np.array([ls1,ls2]) 
print(mat,mat.dtype) # type : 64비트 실수
mat=mat.astype(np.int16)
print(mat,mat.dtype) # type : 16비트 정수

[[ 1.     2.     4.     4.   ]
 [33.3   25.362 74.76  78.19 ]] float64
[[ 1  2  4  4]
 [33 25 74 78]] int16


In [18]:
ls1=[1,2,4,4]
ls2=[33.3,25.362,74.76,78.19]
vec=np.array(ls1)
print(vec, 2*vec, vec/4)
mat=np.array([ls1,ls2])
print(mat)
print(mat, 2*mat, mat+10)

[1 2 4 4] [2 4 8 8] [0.25 0.5  1.   1.  ]
[[ 1.     2.     4.     4.   ]
 [33.3   25.362 74.76  78.19 ]]
[[ 1.     2.     4.     4.   ]
 [33.3   25.362 74.76  78.19 ]] [[  2.      4.      8.      8.   ]
 [ 66.6    50.724 149.52  156.38 ]] [[11.    12.    14.    14.   ]
 [43.3   35.362 84.76  88.19 ]]


In [19]:
ls1=[1,2,4,4]
ls2=[33.3,25.362,74.76,78.19]
vec1=np.array(ls1)
vec2=np.array(ls2)
print(vec1*vec2) #안의 원소끼리 곱하

[ 33.3    50.724 299.04  312.76 ]


In [20]:
ls1=[1,2,4,4]
ls2=[33.3,25.362,74.76,78.19]
vec1=np.array([ls1,ls2])
vec2=np.array([[2,5,1,2],[3,1,4,7]])
print(vec1*vec2) #안의 원소끼리 곱하기. 일반적인 행렬의 곱이 아님

[[  2.     10.      4.      8.   ]
 [ 99.9    25.362 299.04  547.33 ]]


In [21]:
ls1=[1,2,4,77,2,9,5,4,3]
ls2=[33.3,25.362,74.76,78.19]
vec=np.array(ls1)
print(ls1[4],vec[4])

2 2


In [22]:
ls1=[1,2,4,77,2,9,5,4,3]
ls2=[33.3,25.362,74.76,78.19]
vec=np.array(ls1)
print(ls1, "\t", vec)
print(ls1[4], "\t", vec[4])
print(ls1[2:5], "\t", vec[2:5]) # 동일

[1, 2, 4, 77, 2, 9, 5, 4, 3] 	 [ 1  2  4 77  2  9  5  4  3]
2 	 2
[4, 77, 2] 	 [ 4 77  2]


In [23]:
ls1=[1,2,4,77,2,9,5,4,3]
ls2=[33.3,25.362,74.76,78.19]
vec=np.array(ls1)
ls1[4]=999; vec[4]=999 # 동일
print(ls1, "\t", vec) 
ls1[3:6]=[999]; vec[3:6]=999 # 다름 - 리스트는 3,4,5자리를 합쳐 999. 벡터는 각각 999로 바
print(ls1, "\t", vec) 

[1, 2, 4, 77, 999, 9, 5, 4, 3] 	 [  1   2   4  77 999   9   5   4   3]
[1, 2, 4, 999, 5, 4, 3] 	 [  1   2   4 999 999 999   5   4   3]


In [24]:
ls1=[1,2,4,77,2,9,5,4,3]
ls2=[33.3,25.362,74.76,78.19]
vec=np.array(ls1)
sub_vec1=vec[2:6]
print(vec,"\t",sub_vec1)
sub_vec1[2]=9999 # sub vector의 값을 바꾸면 원래 벡터의 값도 바
print(vec,"\t",sub_vec1)

[ 1  2  4 77  2  9  5  4  3] 	 [ 4 77  2  9]
[   1    2    4   77 9999    9    5    4    3] 	 [   4   77 9999    9]


In [25]:
ls1=[1,2,4,77,2,9,5,4,3]
ls2=[33.3,25.362,74.76,78.19]
vec=np.array(ls1)
sub_vec1=vec[2:6]
sub_vec2=vec[2:6].copy() # 다른 객체로 생성
print(vec,"\t",sub_vec1,sub_vec2)
sub_vec1[2]=9999 
print(vec,"\t",sub_vec1,sub_vec2)

[ 1  2  4 77  2  9  5  4  3] 	 [ 4 77  2  9] [ 4 77  2  9]
[   1    2    4   77 9999    9    5    4    3] 	 [   4   77 9999    9] [ 4 77  2  9]


In [26]:
ls1=[1,2,4,7,2,9,5,4,3]
ls2=[33.3,25.362,74.76,78.19,34.6,43.6,90.2,57.3,25.6]
ls3=[10,20,40,20,60,30,20,10,80]
A=np.array([ls1,ls2,ls3])
print(A,"\n")
print(A[1],"\n") #1번 행
print(A[:2],"\n") #0,1번 행
print(A[1,5],"\n") #1행 5열
print(A[1][5],"\n") #위와 동일
print(A[:2,2:5]) #0,1행+2~4열

[[ 1.     2.     4.     7.     2.     9.     5.     4.     3.   ]
 [33.3   25.362 74.76  78.19  34.6   43.6   90.2   57.3   25.6  ]
 [10.    20.    40.    20.    60.    30.    20.    10.    80.   ]] 

[33.3   25.362 74.76  78.19  34.6   43.6   90.2   57.3   25.6  ] 

[[ 1.     2.     4.     7.     2.     9.     5.     4.     3.   ]
 [33.3   25.362 74.76  78.19  34.6   43.6   90.2   57.3   25.6  ]] 

43.6 

43.6 

[[ 4.    7.    2.  ]
 [74.76 78.19 34.6 ]]


In [27]:
print(A[:2,2:5], "\n") #0,1행+2~4열
print(A[:2][2:5],"\n") # 위랑 같지 않음

print(A[:2][:,2:5]) #앞에서 뽑힌 모든 행이라는 의미로 ":,"을 덧붙여줘야함

[[ 4.    7.    2.  ]
 [74.76 78.19 34.6 ]] 

[] 

[[ 4.    7.    2.  ]
 [74.76 78.19 34.6 ]]


In [28]:
ls11=[1,2,5,3]; ls12=[10,40,20,60]; ls13=[4,2,5,4]
ls21=[0,3,1,6]; ls22=[12,32,67,35]; ls23=[7,1,2,9]
arr3d=np.array([[ls11,ls12,ls13],[ls21,ls22,ls23]])
print(arr3d,"\n") # 3차원 배열
print(arr3d[0,1,3], "\t", arr3d[0][1,3], "\n")
print(arr3d[0],"\n", arr3d[0,:2,:3])

[[[ 1  2  5  3]
  [10 40 20 60]
  [ 4  2  5  4]]

 [[ 0  3  1  6]
  [12 32 67 35]
  [ 7  1  2  9]]] 

60 	 60 

[[ 1  2  5  3]
 [10 40 20 60]
 [ 4  2  5  4]] 
 [[ 1  2  5]
 [10 40 20]]


In [29]:
ls11=[1,2,5,3]; ls12=[10,40,20,60]; ls13=[4,2,5,4]
ls21=[0,3,1,6]; ls22=[12,32,67,35]; ls23=[7,1,2,9]
arr3d=np.array([[ls11,ls12,ls13],[ls21,ls22,ls23]])
sub_arr1=arr3d[:2,1] # 값공유 -값 바꾸면 원래거랑 같이 바뀜
sub_arr2=arr3d[:2,1].copy() #복사 - 원래거에 영향안줌
arr3d[1,1,2]=9999
print(arr3d,"\n",sub_arr1, "\n",sub_arr2)

[[[   1    2    5    3]
  [  10   40   20   60]
  [   4    2    5    4]]

 [[   0    3    1    6]
  [  12   32 9999   35]
  [   7    1    2    9]]] 
 [[  10   40   20   60]
 [  12   32 9999   35]] 
 [[10 40 20 60]
 [12 32 67 35]]


In [30]:
ls11=[1,2,5,3]; ls12=[10,40,20,60]; ls13=[4,2,5,4]
ls21=[0,3,1,6]; ls22=[12,32,67,35]; ls23=[7,1,2,9]
mat1=np.array([ls11,ls12,ls13])
print(mat1, "\n")
print(mat1[1],"\n",mat1[[False,True,False]]) # 논리값을 이용한 인덱싱과 슬라이싱

[[ 1  2  5  3]
 [10 40 20 60]
 [ 4  2  5  4]] 

[10 40 20 60] 
 [[10 40 20 60]]


In [31]:
ls11=[1,2,5,3]; ls12=[10,40,20,60]; ls13=[4,2,5,4]
ls21=[0,3,1,6]; ls22=[12,32,67,35]; ls23=[7,1,2,9]
mat1=np.array([ls11,ls12,ls13])
print(mat1, "\n")
print(mat1>=10,"\n")
print(mat1[1],"\n",mat1[mat1>=10],"\n") # 논리값을 이용한 인덱싱과 슬라이싱
print(mat1>=5,"\n")
print(mat1[1],"\n",mat1[mat1>=5])  #이건 행렬로 만들 수 없으니 벡터형으로 돌려줌.

[[ 1  2  5  3]
 [10 40 20 60]
 [ 4  2  5  4]] 

[[False False False False]
 [ True  True  True  True]
 [False False False False]] 

[10 40 20 60] 
 [10 40 20 60] 

[[False False  True False]
 [ True  True  True  True]
 [False False  True False]] 

[10 40 20 60] 
 [ 5 10 40 20 60  5]


In [32]:
gender=np.array(["남","여","여","남","남","여"])
ls11=[1,2,5,3]; ls12=[10,40,20,60]; ls13=[4,2,5,4]
ls21=[3,2,6,7]; ls22=[104,203,435,205]; ls23=[111,324,654,654]
mat=np.array([ls11,ls12,ls13,ls21,ls22,ls23])
print(gender,"\n",mat,"\n")

##이 상황에서 남자 여자 분류하려고함

result=gender=="남"
print(result,"\n")

male=mat[result]
female=mat[~result]
print(male,"\n",female) # 조건에 맞는 값 추출 가능

['남' '여' '여' '남' '남' '여'] 
 [[  1   2   5   3]
 [ 10  40  20  60]
 [  4   2   5   4]
 [  3   2   6   7]
 [104 203 435 205]
 [111 324 654 654]] 

[ True False False  True  True False] 

[[  1   2   5   3]
 [  3   2   6   7]
 [104 203 435 205]] 
 [[ 10  40  20  60]
 [  4   2   5   4]
 [111 324 654 654]]


In [33]:
gender=np.array(["남","여","여","남","남","여"])
ls11=[1,2,5,3]; ls12=[10,40,20,60]; ls13=[4,2,5,4]
ls21=[3,2,6,7]; ls22=[104,203,435,205]; ls23=[111,324,654,654]
mat=np.array([ls11,ls12,ls13,ls21,ls22,ls23])
print(gender,"\n",mat,"\n")

print(mat[mat<10]*10,"\n") #조건에 맞는 값 수정 가능
print(mat<10,"\n")

mat[mat<10]=0 #10보다 작은 값 0으로 대체 가능
print(mat)

['남' '여' '여' '남' '남' '여'] 
 [[  1   2   5   3]
 [ 10  40  20  60]
 [  4   2   5   4]
 [  3   2   6   7]
 [104 203 435 205]
 [111 324 654 654]] 

[10 20 50 30 40 20 50 40 30 20 60 70] 

[[ True  True  True  True]
 [False False False False]
 [ True  True  True  True]
 [ True  True  True  True]
 [False False False False]
 [False False False False]] 

[[  0   0   0   0]
 [ 10  40  20  60]
 [  0   0   0   0]
 [  0   0   0   0]
 [104 203 435 205]
 [111 324 654 654]]


In [34]:
ex=np.random.randn(7,5)
print(ex,"\n")
print(ex[[5,0,2],[3,1,4]],"\n\n",ex[[5,0,2]][:,[3,1,4]]) 
#5행 3열, 0행1열, 2행4열 뽑음 / 5행의 3,1,4열, 0행의 3,1,4열 이런식으로 뽑음

[[-0.13014938  0.69358316 -1.00593982 -0.66332942 -1.34500065]
 [-1.71026042 -0.20593122  0.46371448 -3.21499102  2.16175731]
 [ 0.03723059  0.13681185  0.61508708  1.12230507  0.81109664]
 [-1.15141743 -0.32741229 -0.32193327  0.04331723  1.66471423]
 [-0.45750994  0.76848434 -0.94828413 -0.24094546  0.38523596]
 [ 0.57137016  0.65802574  0.78266147  0.88224178  0.73538028]
 [ 0.27729955  0.5772262   0.70061758 -0.92752541  0.27433218]] 

[0.88224178 0.69358316 0.81109664] 

 [[ 0.88224178  0.65802574  0.73538028]
 [-0.66332942  0.69358316 -1.34500065]
 [ 1.12230507  0.13681185  0.81109664]]


In [35]:
ex=np.arange(24).reshape(2,4,3)
print(ex, "\n\n", ex.transpose(), "\n\n", ex.transpose(2,0,1))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]] 

 [[[ 0 12]
  [ 3 15]
  [ 6 18]
  [ 9 21]]

 [[ 1 13]
  [ 4 16]
  [ 7 19]
  [10 22]]

 [[ 2 14]
  [ 5 17]
  [ 8 20]
  [11 23]]] 

 [[[ 0  3  6  9]
  [12 15 18 21]]

 [[ 1  4  7 10]
  [13 16 19 22]]

 [[ 2  5  8 11]
  [14 17 20 23]]]


In [36]:
ex=np.arange(24).reshape(2,4,3)
print(ex.transpose(1,0,2), "\n\n", ex.swapaxes(1,0)) #동

[[[ 0  1  2]
  [12 13 14]]

 [[ 3  4  5]
  [15 16 17]]

 [[ 6  7  8]
  [18 19 20]]

 [[ 9 10 11]
  [21 22 23]]] 

 [[[ 0  1  2]
  [12 13 14]]

 [[ 3  4  5]
  [15 16 17]]

 [[ 6  7  8]
  [18 19 20]]

 [[ 9 10 11]
  [21 22 23]]]


In [37]:
ex=np.arange(24).reshape(2,4,3)
np.array([1,4,2,np.inf,np.nan]) #무한대값, NA값

array([ 1.,  4.,  2., inf, nan])

In [38]:
A=np.arange(18).reshape(3,6)
B=np.random.randn(3,6)
print(A,"\n",B)
print(np.abs(B)) #음수를 양수로
print(np.sign(B)) #음수는 -1, 양수는 1
print(np.isfinite(B)) #각각의 원소가 무한인지, 유한인지 판단

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 
 [[ 1.27728114 -0.23223773  0.95220891 -0.00987384 -0.22701706 -1.26668899]
 [-0.68612289  1.83906004 -0.95510073 -0.6263894  -1.1569747  -0.31945667]
 [ 0.73650282 -0.18270208 -0.53147079 -1.52155732  0.32561023 -0.28642848]]
[[1.27728114 0.23223773 0.95220891 0.00987384 0.22701706 1.26668899]
 [0.68612289 1.83906004 0.95510073 0.6263894  1.1569747  0.31945667]
 [0.73650282 0.18270208 0.53147079 1.52155732 0.32561023 0.28642848]]
[[ 1. -1.  1. -1. -1. -1.]
 [-1.  1. -1. -1. -1. -1.]
 [ 1. -1. -1. -1.  1. -1.]]
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


In [39]:
print(np.square(A))
print(A**2) # 위의 식과 동일

[[  0   1   4   9  16  25]
 [ 36  49  64  81 100 121]
 [144 169 196 225 256 289]]
[[  0   1   4   9  16  25]
 [ 36  49  64  81 100 121]
 [144 169 196 225 256 289]]


In [40]:
print(np.add(A,B))
print(A+B)  # 위의 식과 동일

[[ 1.27728114  0.76776227  2.95220891  2.99012616  3.77298294  3.73331101]
 [ 5.31387711  8.83906004  7.04489927  8.3736106   8.8430253  10.68054333]
 [12.73650282 12.81729792 13.46852921 13.47844268 16.32561023 16.71357152]]
[[ 1.27728114  0.76776227  2.95220891  2.99012616  3.77298294  3.73331101]
 [ 5.31387711  8.83906004  7.04489927  8.3736106   8.8430253  10.68054333]
 [12.73650282 12.81729792 13.46852921 13.47844268 16.32561023 16.71357152]]


In [41]:
print(np.multiply(A,B))
print(A*B)  # 위의 식과 동일

[[  0.          -0.23223773   1.90441781  -0.02962152  -0.90806824
   -6.33344494]
 [ -4.11673732  12.87342031  -7.64080585  -5.63750462 -11.56974704
   -3.51402337]
 [  8.83803381  -2.37512704  -7.44059102 -22.82335978   5.20976373
   -4.86928415]]
[[  0.          -0.23223773   1.90441781  -0.02962152  -0.90806824
   -6.33344494]
 [ -4.11673732  12.87342031  -7.64080585  -5.63750462 -11.56974704
   -3.51402337]
 [  8.83803381  -2.37512704  -7.44059102 -22.82335978   5.20976373
   -4.86928415]]


In [42]:
print(np.power(A,B))
print(A**B)  # 위의 식과 동일

[[0.00000000e+00 1.00000000e+00 1.93483281e+00 9.89211101e-01
  7.29998740e-01 1.30203420e-01]
 [2.92477605e-01 3.58249868e+01 1.37232853e-01 2.52506525e-01
  6.96667090e-02 4.64857841e-01]
 [6.23476413e+00 6.25864376e-01 2.45961102e-01 1.62371476e-02
  2.46645836e+00 4.44185509e-01]]
[[0.00000000e+00 1.00000000e+00 1.93483281e+00 9.89211101e-01
  7.29998740e-01 1.30203420e-01]
 [2.92477605e-01 3.58249868e+01 1.37232853e-01 2.52506525e-01
  6.96667090e-02 4.64857841e-01]
 [6.23476413e+00 6.25864376e-01 2.45961102e-01 1.62371476e-02
  2.46645836e+00 4.44185509e-01]]


In [43]:
print(np.greater(A,B)) #A>B
print(A>B)  # 위의 식과 동일

[[False  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
[[False  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


In [44]:
print((B>=0) & (B<2)) # B>=0 and B<2 로 치면 안됨. 왜안되는지는 아직 모름.

[[ True False  True False False False]
 [False  True False False False False]
 [ True False False False  True False]]


In [45]:
print(B[(B>=0) & (B<2)]) # 0<=B<2인것만 추

[1.27728114 0.95220891 1.83906004 0.73650282 0.32561023]


In [46]:
print(np.logical_and((B>=0),(B<2)))

[[ True False  True False False False]
 [False  True False False False False]
 [ True False False False  True False]]


In [47]:
np.where([True,False,True],[1,2,3],[-9,-8,-7]) #원래라면 조건식이 들어가야함

array([ 1, -8,  3])

In [48]:
np.where([[True,False],
          [True, True]],
          [[1,2],
           [3,4]],
          [[-9,-8],
           [-7,-6]])  #2차원도 가

array([[ 1, -8],
       [ 3,  4]])

In [49]:
A=np.array([2,5,3,6,7,33])
B=np.array([3,6,4,6,7])
print(np.mean(A), np.mean(B))
print(A.mean(), B.mean()) # 둘다 가능

print(A.std(ddof=0),np.std(A,ddof=0))
print(A.std(ddof=0),np.std(A,ddof=1))
print(A.std()) # 아무것도 안적으면 default 는 n으로 나눈 것

9.333333333333334 5.2
9.333333333333334 5.2
10.71862346054235 10.71862346054235
10.71862346054235 11.74166370948626
10.71862346054235


In [50]:
A=np.array([2,5,3,6,7,33])
B=np.array([3,6,4,6,7])
print(A.argmax(),A.argmin()) # 최소값의 인덱스. 최대값의 인덱스

5 0


In [51]:
A=np.array([[2,5,3],[6,7,33],[4,2,7],[7,9,4]])
B=np.array([2,5,3,6,7,33,4,2,7,7,9,4])
print(A.mean(),np.mean(A)) #아무인수없이 쓰면 전체에 대해 평균값 구해

7.416666666666667 7.416666666666667


In [52]:
A=np.array([[2,5,3],[6,7,33],[4,2,7],[7,9,4]])
B=np.array([2,5,3,6,7,33,4,2,7,7,9,4])
print(A.mean(axis=0),np.mean(A,axis=1)) #열평균 # 행평균

[ 4.75  5.75 11.75] [ 3.33333333 15.33333333  4.33333333  6.66666667]


In [53]:
A=np.array([[2,5,3],[6,7,33],[4,2,7],[7,9,4]])
B=np.array([2,5,3,6,7,33,4,2,7,7,9,4])
print(A.std(axis=0,ddof=1),np.std(A,axis=1,ddof=1)) #열표준편차 # 행표준편차

[ 2.21735578  2.98607881 14.26826315] [ 1.52752523 15.30795     2.51661148  2.51661148]


In [54]:
A=np.array([[2,5,3],[6,7,33],[4,2,7],[7,9,4]])
B=np.array([2,5,3,6,7,33,4,2,7,7,9,4])
print(B>=5) # 얘도 배열임!
print((B>=5).shape, (B>=5).dtype) # 배열의 특성 지님 -> 배열의 연산 가능
print((B>=5).sum()) # 자동적으로 논리값이 숫자로 cast되면서, 5이상인건 1, 5미만인건 0이됨. 그말은 저 값의 의미는 5이상인 값의 갯수
print((B>=5).mean()) # B>=5인 값은 1, B<5인 것은 0이므로 평균내면 5이상인거의 비율나타남

[False  True False  True  True  True False False  True  True  True False]
(12,) bool
7
0.5833333333333334


In [55]:
A=np.array([[2,5,3],[6,7,33],[4,2,7],[7,9,4]])
B=np.array([2,5,3,6,7,33,4,2,7,7,9,4])
print(np.sort(B),B) #함수로 쓰면 B의 값이 바뀌지 않음
print(B.sort(),B) #메소드를 사용하면 B의 값이 바뀜

[ 2  2  3  4  4  5  6  7  7  7  9 33] [ 2  5  3  6  7 33  4  2  7  7  9  4]
None [ 2  2  3  4  4  5  6  7  7  7  9 33]


In [3]:
npy_AB=np.load("C:/Users/Affinity/Desktop/Python_Data/ch02_data/arr_AB.npz")
npy_AB

In [4]:
npy_AB["A2d"] # load 후 불러올때는 키워드를 사용

array([[ 2,  5,  3],
       [ 6,  7, 33],
       [ 4,  2,  7],
       [ 7,  9,  4]])

In [5]:
npy_AB["B1d"]

array([ 2,  5,  3,  6,  7, 33,  4,  2,  7,  7,  9,  4])

In [6]:
A=np.loadtxt("C:/Users/Affinity/Desktop/Python_Data/ch02_data/steel.txt",
         skiprows=5, delimiter="\t")
print(A)

[[ 81.4 195.   57. ]
 [122.2 179.   61. ]
 [101.7 205.   60. ]
 [175.6 204.   62. ]
 [150.3 201.   61. ]
 [ 64.8 184.   54. ]
 [ 92.1 210.   58. ]
 [113.8 209.   61. ]]


In [7]:
print(A.mean(axis=0)) # 열평균 # Y:강도, X1:온도, X2:압력이므로, mean한거보면 평균강도, 평균온도, 평균압력구한것임

[112.7375 198.375   59.25  ]


In [8]:
A=np.loadtxt("C:/Users/Affinity/Desktop/Python_Data/ch02_data/steel.txt",
         skiprows=5, delimiter="\t", usecols=(0,2), unpack=True) # usecols에 따라 불러올 인덱스 지정 # unpack 옵션으로 전치된 자료 불러오기
print(A)

[[ 81.4 122.2 101.7 175.6 150.3  64.8  92.1 113.8]
 [ 57.   61.   60.   62.   61.   54.   58.   61. ]]


In [13]:
A=np.arange(8).reshape(4,2)
B=np.array([[3,5,7,2],[4,3,6,2]])
C=np.array([[5,3,6,4],[7,6,4,5],[5,8,4,2],[6,5,3,7]])
print(A);print(B);print(C)
print(np.dot(B,A),np.diag(C)) #행렬곱 #대각성

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[3 5 7 2]
 [4 3 6 2]]
[[5 3 6 4]
 [7 6 4 5]
 [5 8 4 2]
 [6 5 3 7]]
[[50 67]
 [42 57]] [5 6 4 7]


In [15]:
print(np.linalg.inv(C), np.dot(C,np.linalg.inv(C))) # 정확하게 항등행렬이 나오는것은 아님. 실수계산오차발생.

[[-0.13168724  0.79835391 -0.29218107 -0.41152263]
 [-0.06995885 -0.26337449  0.25102881  0.1563786 ]
 [ 0.28395062 -0.28395062  0.09876543  0.01234568]
 [ 0.04115226 -0.3744856   0.02880658  0.37860082]] [[ 1.00000000e+00  8.88178420e-16  0.00000000e+00  0.00000000e+00]
 [ 5.55111512e-17  1.00000000e+00  0.00000000e+00  4.44089210e-16]
 [-1.11022302e-16  8.88178420e-16  1.00000000e+00  4.44089210e-16]
 [ 5.55111512e-17  0.00000000e+00  4.44089210e-16  1.00000000e+00]]


In [18]:
print(np.rint(np.dot(C,np.linalg.inv(C))))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [7]:
steel=np.loadtxt("C:/Users/Affinity/Desktop/Python_Data/ch02_data/steel.txt",
         skiprows=5, delimiter="\t") 
y=steel[:,0].copy()
X=steel.copy()
X[:,0]=1 #이렇게 꼭 1로 맞춰줘야하나,,,?
print(steel,X,y)
np.linalg.lstsq(X,y) #첫번째께 회귀계수, 두번째께 SSE, 세번째께 SVD분해 시, 대각행렬의 대각선값=eigenvalue의 제곱근

b=np.linalg.lstsq(X,y)[0]
New_x=np.array([1,200,60]) #회귀값 대입할때 상수쪽인 1을 먼저 대입하고 그다음 x, y 대입
print(b,New_x,b*New_x,np.sum(b*New_x)) #같은 위치의 성분끼리 곱함 #온도가 200이고, 강도가 60일 때, 회귀값

[[ 81.4 195.   57. ]
 [122.2 179.   61. ]
 [101.7 205.   60. ]
 [175.6 204.   62. ]
 [150.3 201.   61. ]
 [ 64.8 184.   54. ]
 [ 92.1 210.   58. ]
 [113.8 209.   61. ]] [[  1. 195.  57.]
 [  1. 179.  61.]
 [  1. 205.  60.]
 [  1. 204.  62.]
 [  1. 201.  61.]
 [  1. 184.  54.]
 [  1. 210.  58.]
 [  1. 209.  61.]] [ 81.4 122.2 101.7 175.6 150.3  64.8  92.1 113.8]
[-5.54311223e+02 -1.79739607e-01  1.18599927e+01] [  1 200  60] [-554.31122321  -35.94792132  711.59956219] 121.34041766671066


C:\ProgramData\Anaconda3\envs\mypython\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  import sys
C:\ProgramData\Anaconda3\envs\mypython\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  if __name__ == '__main__':


In [8]:
np.random.randn(100) # 표준정규분포에서 난수 발생.

array([ 1.73919585,  0.50599101, -0.26687567,  1.23856025, -0.32294896,
       -0.01788394, -0.24303828, -0.29062318,  0.35343799, -0.46611075,
       -0.09703844, -0.67254183,  1.25056213, -0.24011036, -0.19528616,
       -1.00240569, -1.18454009, -1.86219704, -2.47810331, -0.30566062,
        0.56781602,  0.63782422, -1.16539407,  0.86624232, -1.66642432,
       -0.72210704, -0.41908173,  2.31806048, -1.71908065,  0.59330108,
       -0.291832  ,  0.97589165,  0.09934599,  0.20355159,  0.98667732,
       -0.71055382,  1.24367292,  0.04315909,  0.92117838,  0.17057704,
       -0.85253291, -0.18210235, -0.04849096, -1.47358538, -0.17550988,
        0.42982689, -1.76789614, -1.75165023,  0.90605788,  2.42367493,
       -0.54990433, -0.20866008,  1.39972106, -0.16304727,  0.50333425,
        0.65440624, -0.46231803,  0.1069416 ,  1.22423412, -0.90860007,
       -0.33953471,  0.44870075,  1.45735046,  0.16270114,  0.32678353,
       -1.18681404, -1.80237794,  0.28654284,  2.00919131, -1.29

In [10]:
np.random.normal(loc=20,scale=2,size=100) # 모평균 : loc, 모표준편 : scale

array([15.54606227, 20.71682097, 20.96217087, 17.28308818, 22.24693366,
       19.31684116, 15.43784335, 17.57596682, 18.02291441, 19.07273027,
       19.65563745, 19.9113746 , 19.17809522, 20.50356151, 19.65843283,
       20.29155415, 21.23047931, 21.81941269, 20.53801035, 18.79135926,
       26.47783259, 23.44883749, 15.98003733, 20.54731802, 18.0130708 ,
       20.90282091, 18.57175807, 20.0311379 , 21.72030198, 18.64065245,
       19.92458099, 20.70663278, 19.08802812, 18.95272051, 18.90973492,
       22.28129167, 20.3289863 , 20.03185354, 19.63413819, 22.0141818 ,
       21.15235539, 22.10922422, 19.04163592, 19.76330474, 16.30814481,
       23.92655232, 18.91913307, 20.48990231, 17.04321672, 22.65978148,
       20.3945803 , 20.22340721, 23.28873483, 20.92910401, 18.33601603,
       20.75840373, 18.62803268, 21.15179837, 18.19112223, 17.78657517,
       19.75987961, 23.2549974 , 19.98389457, 19.35008328, 18.25620038,
       19.74581199, 18.3591694 , 20.44362543, 17.46014979, 16.82

In [64]:
x=np.array([[1,3,6],[1,5,4],[1,3,6],[1,4,6],[1,7,3],[1,8,4],[1,9,7],[1,3,6],[1,5,2],[1,7,6]])
print(x.shape,"\n")
beta=np.array([1,-2.5,5.5])
e=np.random.normal(loc=0,scale=2,size=10)
y=np.dot(x,beta)+e
print(x,"\n",beta,"\n",y,"\n")
np.linalg.lstsq(x,y)

(10, 3) 

[[1 3 6]
 [1 5 4]
 [1 3 6]
 [1 4 6]
 [1 7 3]
 [1 8 4]
 [1 9 7]
 [1 3 6]
 [1 5 2]
 [1 7 6]] 
 [ 1.  -2.5  5.5] 
 [27.33761383  4.64475994 26.33692771 24.87434807 -0.59560571  1.36159678
 18.01011745 29.68483392  3.54460502 19.2632266 ] 



C:\ProgramData\Anaconda3\envs\mypython\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  import sys


(array([ 1.02384185, -2.63505021,  5.73033433]),
 array([69.65011522]),
 3,
 array([24.13008397,  6.1037028 ,  0.6956002 ]))

In [65]:
x=np.array([[1,3,6],[1,5,4],[1,3,6],[1,4,6],[1,7,3],[1,8,4],[1,9,7],[1,3,6],[1,5,2],[1,7,6]])
print(x.shape,"\n")
beta=np.array([1,-2.5,5.5])
np.random.seed(1234) # 시드값 설정 - 고정
e=np.random.normal(loc=0,scale=2,size=10)
y=np.dot(x,beta)+e
print(x,"\n",beta,"\n",y,"\n")
np.linalg.lstsq(x,y)

(10, 3) 

[[1 3 6]
 [1 5 4]
 [1 3 6]
 [1 4 6]
 [1 7 3]
 [1 8 4]
 [1 9 7]
 [1 3 6]
 [1 5 2]
 [1 7 6]] 
 [ 1.  -2.5  5.5] 
 [27.44287033  8.11804861 29.36541394 23.37469621 -1.44117747  4.77432588
 18.71917683 25.22695299 -0.46860726 12.01463009] 



C:\ProgramData\Anaconda3\envs\mypython\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


(array([ 0.14457203, -2.5512041 ,  5.66891263]),
 array([43.38911395]),
 3,
 array([24.13008397,  6.1037028 ,  0.6956002 ]))