In [3]:
from pandas import Series, DataFrame # 이걸 안적으면 pd.Series이런식으로 다 적어야함!
import pandas as pd
import numpy as np

obj=Series([14,-27,35,73])
print("Series\n{0}\n\nvalue\n{1}\n\nindex\n{2}".format(obj,obj.values,obj.index))

Series
0    14
1   -27
2    35
3    73
dtype: int64

value
[ 14 -27  35  73]

index
RangeIndex(start=0, stop=4, step=1)


In [4]:
Exam=Series([2,3,4,4],index=["kim","lee","cho","kang"])
Exam.index

Index(['kim', 'lee', 'cho', 'kang'], dtype='object')

In [5]:
Exam["lee"] #인덱스를 통해 자료 접근 가능

3

In [6]:
Exam[["lee","kang"]] #여러개의 인덱스도 접근 가능. 

lee     3
kang    4
dtype: int64

In [7]:
Exam=Series([2,3,6,9,3,5,7,9,3,1],index=["A","B","C","D","E","F","G","H","I","J"])
b_Result=(Exam>=4) & (Exam<8)  #논리값을 이용해서 데이터에 접근 가능
b_Result

A    False
B    False
C     True
D    False
E    False
F     True
G     True
H    False
I    False
J    False
dtype: bool

In [8]:
Exam[b_Result]

C    6
F    5
G    7
dtype: int64

In [9]:
# 굳이 변수만들필요없음
Exam[((Exam>=4) & (Exam<8))]

C    6
F    5
G    7
dtype: int64

In [10]:
np.sqrt(Exam[((Exam>=4) & (Exam<8))]) # numpy 함수도 사용 가능

C    2.449490
F    2.236068
G    2.645751
dtype: float64

In [11]:
dic={"kim":25,"lee":45,"cho":13}
Exam=Series(dic)
Exam  #사전과 시리즈는 유사

kim    25
lee    45
cho    13
dtype: int64

In [12]:
Exam=Series(dic,index=["lee","kang","cho","kim"])
Exam

lee     45.0
kang     NaN
cho     13.0
kim     25.0
dtype: float64

In [13]:
pd.isnull(Exam) #각각에 대해서 결측값이니?

lee     False
kang     True
cho     False
kim     False
dtype: bool

In [14]:
pd.notnull(Exam) # 결측이 아니니?

lee      True
kang    False
cho      True
kim      True
dtype: bool

In [15]:
dic={"kim":25,"lee":45,"cho":13}
Exam1=Series(dic)
Exam2=Series([56,75,85,96],index=["cho","kim","kang","lee"])
print(Exam1, "\n\n", Exam2, "\n\n",Exam1+Exam2)

kim    25
lee    45
cho    13
dtype: int64 

 cho     56
kim     75
kang    85
lee     96
dtype: int64 

 cho      69.0
kang      NaN
kim     100.0
lee     141.0
dtype: float64


In [16]:
dic={"kim":25,"lee":45,"cho":13}
Exam1=Series(dic)
Exam2=Series([56,75,85,96],index=["cho","kim","kang","lee"])
print(Exam1, "\n\n", Exam2)
Result=Exam1+Exam2 #색인같은것끼리 더하기
Result.name="성적" #시리즈에 이름붙일 수 있음
Result

kim    25
lee    45
cho    13
dtype: int64 

 cho     56
kim     75
kang    85
lee     96
dtype: int64


cho      69.0
kang      NaN
kim     100.0
lee     141.0
Name: 성적, dtype: float64

In [17]:
Result.index.name="choi"
Result #색인이름 추가, 빈값

choi
cho      69.0
kang      NaN
kim     100.0
lee     141.0
Name: 성적, dtype: float64

In [18]:
dic={"gender":["M","F","F","M"],"mid":[25,56,35,34],"fin":[45,76,88,79]} #key가 변수명
Exam=DataFrame(dic)
Exam

gender  mid  fin
0      M   25   45
1      F   56   76
2      F   35   88
3      M   34   79

In [19]:
dic={"gender":["M","F","F","M"],"mid":[25,56,35,34],"fin":[45,76,88,79]} #key가 변수명
Exam=DataFrame(dic,columns=["fin","gender","mid"]) # 배열원하는대로 지정 가능
Exam

fin gender  mid
0   45      M   25
1   76      F   56
2   88      F   35
3   79      M   34

In [20]:
dic={"gender":["M","F","F","M"],"mid":[25,56,35,34],"fin":[45,76,88,79]} #key가 변수명
Exam=DataFrame(dic,columns=["fin","gender","mid","NA"]) # 비어있는 열 추가도 가능
Exam

fin gender  mid   NA
0   45      M   25  NaN
1   76      F   56  NaN
2   88      F   35  NaN
3   79      M   34  NaN

In [21]:
dic={"gender":["M","F","F","M"],"mid":[25,56,35,34],"fin":[45,76,88,79]} #key가 변수명
Exam=DataFrame(dic,columns=["fin","gender","mid","NA"],index=["A","B","C","D"]) # 인덱스도 원하는대로 바꿀 수 있음
Exam

fin gender  mid   NA
A   45      M   25  NaN
B   76      F   56  NaN
C   88      F   35  NaN
D   79      M   34  NaN

In [22]:
arr=np.array([[3,5,7,2],[25,56,35,34],[45,76,88,79]])
Exam=DataFrame(arr) # 리스트가 각각 행이 됨 
Exam

0   1   2   3
0   3   5   7   2
1  25  56  35  34
2  45  76  88  79

In [23]:
arr=np.array([[3,5,7,2],[25,56,35,34],[45,76,88,79]])
Exam=DataFrame(arr.T) # 전치시켜서 넣으면 열별로도 가능
Exam

0   1   2
0  3  25  45
1  5  56  76
2  7  35  88
3  2  34  79

In [24]:
arr=np.array([[3,5,7,2],[25,56,35,34],[45,76,88,79]])
Exam=DataFrame(arr.T,columns=["V1","V2","V3"],index=["A","B","C","D"]) # 열, 행인덱스 추가
Exam

V1  V2  V3
A   3  25  45
B   5  56  76
C   7  35  88
D   2  34  79

In [25]:
arr=np.array([[3,5,7,2],[25,56,35,34],[45,76,88,79]])
Exam=DataFrame(arr.T,columns=["V1","V2","V3"],index=["A","B","C","D"]) # 열, 행인덱스 추가
print(Exam.values,"\n\n",Exam.index,"\n\n",Exam.columns) # 값, #행 인덱스 # 열인덱스

[[ 3 25 45]
 [ 5 56 76]
 [ 7 35 88]
 [ 2 34 79]] 

 Index(['A', 'B', 'C', 'D'], dtype='object') 

 Index(['V1', 'V2', 'V3'], dtype='object')


In [26]:
Exam.ix["B"] # 행인덱스를 통해 결과받음. 시리즈값으로 돌려받음

C:\Users\Affinity\Anaconda3\envs\mypython\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


V1     5
V2    56
V3    76
Name: B, dtype: int32

In [27]:
Exam.loc[["B","A"]] # 두개이상의 행을 출력할 때에는 데이터 프레임으로 돌려받음

V1  V2  V3
B   5  56  76
A   3  25  45

In [28]:
Exam.iloc[1] #원래인덱스번호를 이용해서 접근하게 해줌, 1번이면 2번째 행

V1     5
V2    56
V3    76
Name: B, dtype: int32

In [29]:
Exam.iloc[[2,0]] #2,0을 적을 때 []이용

V1  V2  V3
C   7  35  88
A   3  25  45

In [30]:
Exam["V3"] # 열인덱스를 이용

A    45
B    76
C    88
D    79
Name: V3, dtype: int32

In [31]:
Exam.V3

A    45
B    76
C    88
D    79
Name: V3, dtype: int32

In [32]:
Exam[["V3","V2"]] #여러개의 열 추출할 때

V3  V2
A  45  25
B  76  56
C  88  35
D  79  34

In [33]:
Exam.loc[["B","C"],["V2","V3"]] #한꺼번에도 사용 가능

V2  V3
B  56  76
C  35  88

In [34]:
arr=np.array([[3,5,7,2],[25,56,35,34],[45,76,88,79]])
Exam=DataFrame(arr.T,columns=["V1","V2","V3"],index=["A","B","C","D"])
gender=Series(["남","여","남","남"],index=["D","A","E","B"])
print(Exam,"\n\n",gender,"\n") 
Exam["gender"]=gender #열추가한다고 생각하면 됨. #색인을 기준으로 결합 #E는 데이터가 원래 없으므로 빠지게됨
print(Exam)

   V1  V2  V3
A   3  25  45
B   5  56  76
C   7  35  88
D   2  34  79 

 D    남
A    여
E    남
B    남
dtype: object 

   V1  V2  V3 gender
A   3  25  45      여
B   5  56  76      남
C   7  35  88    NaN
D   2  34  79      남


In [35]:
print(Exam.T) #DataFrame도 전치가능

         A   B    C   D
V1       3   5    7   2
V2      25  56   35  34
V3      45  76   88  79
gender   여   남  NaN   남


In [36]:
Exam.iloc[[2,3]][["gender","V1"]]

gender  V1
C    NaN   7
D      남   2

In [37]:
Exam.iloc[[2,3]].gender # 하나의 열 추출할때는 이렇게 해도 가능

C    NaN
D      남
Name: gender, dtype: object

In [38]:
Exam.loc[["C","A"]].gender

C    NaN
A      여
Name: gender, dtype: object

In [39]:
Exam.reindex(["C","A","B","F","D"]) #F는 추가되므로 값자체는 비게해서!

V1    V2    V3 gender
C  7.0  35.0  88.0    NaN
A  3.0  25.0  45.0      여
B  5.0  56.0  76.0      남
F  NaN   NaN   NaN    NaN
D  2.0  34.0  79.0      남

In [40]:
Ex=Series([3,5,2,6])
Ex

0    3
1    5
2    2
3    6
dtype: int64

In [41]:
Ex.reindex([2,0,3,1,5])

2    2.0
0    3.0
3    6.0
1    5.0
5    NaN
dtype: float64

In [42]:
Ex.reindex([2,0,3,1,5],fill_value=0) #없는 인덱스추가할 때 자동으로 값 추가

2    2
0    3
3    6
1    5
5    0
dtype: int64

In [43]:
Ex.reindex([2,0,3,1,5],method="ffill") # 앞의 값으로 채우기

2    2
0    3
3    6
1    5
5    6
dtype: int64

In [44]:
arr=np.array([[3,5,7,2],[25,56,35,34],[45,76,88,79]])
Exam=DataFrame(arr.T,columns=["V1","V2","V3"],index=["A","B","C","D"])
#gender=Series(["남","여","남","남"],index=["D","A","E","B"])
#Exam["gender"]=gender
print(Exam)
Exam.reindex(["C","A","B","F","D"],method="ffill") #원래행렬을 기준으로 앞의 값 채우기. F는 D다음이므로 D를 따라감.

   V1  V2  V3
A   3  25  45
B   5  56  76
C   7  35  88
D   2  34  79


V1  V2  V3
C   7  35  88
A   3  25  45
B   5  56  76
F   2  34  79
D   2  34  79

In [45]:
arr=np.array([[3,5,7,2],[25,56,35,34],[45,76,88,79]])
Exam=DataFrame(arr.T,columns=["V1","V2","V3"],index=["A","B","C","D"])
#gender=Series(["남","여","남","남"],index=["D","A","E","B"]) 
#Exam["gender"]=gender
print(Exam)
Exam.reindex(["C","A","B","F","D"],method="bfill") #원래행렬을 기준으로 뒤의값 채우기. D는 뒤에 뭐가 없으므로 뒤에 표시안되있음.

   V1  V2  V3
A   3  25  45
B   5  56  76
C   7  35  88
D   2  34  79


V1    V2    V3
C  7.0  35.0  88.0
A  3.0  25.0  45.0
B  5.0  56.0  76.0
F  NaN   NaN   NaN
D  2.0  34.0  79.0

In [46]:
arr=np.array([[3,5,7,2],[25,56,35,34],[45,76,88,79]])
Exam=DataFrame(arr.T,columns=["V1","V2","V3"],index=["A","B","C","F"])
#gender=Series(["남","여","남","남"],index=["D","A","E","B"]) 
#Exam["gender"]=gender
print(Exam)
Exam.reindex(["C","A","B","F","E"],method="ffill") #E는 D뒤 F앞으로 들어가므로 D가 기준 

   V1  V2  V3
A   3  25  45
B   5  56  76
C   7  35  88
F   2  34  79


V1  V2  V3
C   7  35  88
A   3  25  45
B   5  56  76
F   2  34  79
E   7  35  88

In [47]:
arr=np.array([[3,5,7,2],[25,56,35,34],[45,76,88,79]])
Exam=DataFrame(arr.T,columns=["V1","V2","V3"],index=["A","B","C","F"])
#gender=Series(["남","여","남","남"],index=["D","A","E","B"]) 
#Exam["gender"]=gender
print(Exam)
Exam.reindex(["C","A","B","F","E"],method="bfill") #E는 D뒤 F앞으로 들어가므로 F가 기준 

   V1  V2  V3
A   3  25  45
B   5  56  76
C   7  35  88
F   2  34  79


V1  V2  V3
C   7  35  88
A   3  25  45
B   5  56  76
F   2  34  79
E   2  34  79

In [48]:
Exam.reindex(columns=["att","V1","V2","V3"],method="bfill") #열쪽 재배열할때는 method사용 불가

att  V1  V2  V3
A  NaN   3  25  45
B  NaN   5  56  76
C  NaN   7  35  88
F  NaN   2  34  79

In [49]:
df=Exam.reindex(columns=["att","V1","V2","V3"],fill_value=999)
print("데이터프레임 :\n{0}".format(df))
df.drop(["C"]) # C인덱스갖는 열삭제

데이터프레임 :
   att  V1  V2  V3
A  999   3  25  45
B  999   5  56  76
C  999   7  35  88
F  999   2  34  79


att  V1  V2  V3
A  999   3  25  45
B  999   5  56  76
F  999   2  34  79

In [50]:
arr=np.array([[3,5,7,2],[25,56,35,34],[45,76,88,79]])
Exam=DataFrame(arr.T,columns=["V1","V2","V3"],index=["A","B","C","F"])
df=Exam.reindex(columns=["att","V1","V2","V3"],fill_value=999)
print("데이터프레임 :\n{0}".format(df))

df.drop(["C"],axis=0) #행 삭제

데이터프레임 :
   att  V1  V2  V3
A  999   3  25  45
B  999   5  56  76
C  999   7  35  88
F  999   2  34  79


att  V1  V2  V3
A  999   3  25  45
B  999   5  56  76
F  999   2  34  79

In [51]:
#행삭제, 열삭제한다해서 원본이 바뀌지는 않음

df.drop(["V1"],axis=1) #열 삭제

att  V2  V3
A  999  25  45
B  999  56  76
C  999  35  88
F  999  34  79

In [5]:
Ex=Series([3,5,2,6])
Ex.reindex([2,0,3,5,1],method="ffill")
print(Ex, "\n\n", Ex[[1,0,2]])

0    3
1    5
2    2
3    6
dtype: int64 

 1    5
0    3
2    2
dtype: int64


In [10]:
Ex=Series([3,5,2,6,3])
Ex=Ex.reindex([2,0,3,5,1],method="ffill")
print(Ex)
b_data=[True,False,False,True,True] #데이터길이에 맞게끔만 하면됨. 논리값넣으면 값추출됨
print(b_data)
print(Ex, "\n\n", Ex[b_data])

2    2
0    3
3    6
5    3
1    5
dtype: int64
[True, False, False, True, True]
2    2
0    3
3    6
5    3
1    5
dtype: int64 

 2    2
5    3
1    5
dtype: int64


In [11]:
Ex=Series([3,5,2,6])
Ex=Ex.reindex([2,0,3,5,1],method="ffill")
b_data=(Ex>=3.5) #데이터길이에 맞게끔만 하면됨. 논리값넣으면 값추출됨
print(b_data)
print(Ex, "\n\n", Ex[b_data])

2    False
0    False
3     True
5     True
1     True
dtype: bool
2    2
0    3
3    6
5    6
1    5
dtype: int64 

 3    6
5    6
1    5
dtype: int64


In [26]:
x=np.random.rand(100)
gender=np.where(x>0.5,"M","F")
height=np.rint(np.random.normal(loc=175,scale=6,size=100))
weight=np.rint(np.random.normal(loc=68,scale=3,size=100))
DF=DataFrame(np.array([gender,height,weight]).T,columns=["gender","height","weight"]) #array로 만들었기 때문에 다 문자로 바뀜
#이런 식으로 데이터가 있다고 가정
np.random.seed(12298) #없어도되는 코드. 그냥 편의상고정해놓음.
rand_num=np.random.rand(100) #0에서 1사이의 수 뽑음 
#90%는 train, 10%는 test뽑는다고 하면,
select=rand_num<0.9
np.sum(select) # 약 90프로가 속함.
select

array([False,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True, False, False,  True,  True,  True,  True,
        True])

In [28]:
trainDF=DF[select] # 85개의 train data 뽑힘.
trainDF

gender height weight
1       F  180.0   71.0
2       F  166.0   67.0
3       M  173.0   73.0
4       F  187.0   66.0
6       F  174.0   66.0
8       F  177.0   67.0
9       F  175.0   67.0
10      F  172.0   64.0
11      M  175.0   66.0
12      F  178.0   68.0
13      M  184.0   67.0
15      F  171.0   69.0
16      M  171.0   74.0
17      F  177.0   68.0
18      M  177.0   70.0
19      F  161.0   67.0
20      F  178.0   64.0
21      M  189.0   65.0
22      F  177.0   66.0
23      F  176.0   70.0
24      F  169.0   69.0
25      F  181.0   67.0
26      M  182.0   64.0
27      F  186.0   69.0
28      M  172.0   68.0
29      M  189.0   72.0
30      F  177.0   71.0
31      M  176.0   67.0
32      F  163.0   70.0
33      F  185.0   67.0
..    ...    ...    ...
62      M  176.0   70.0
64      F  169.0   69.0
65      F  173.0   71.0
66      F  184.0   68.0
67      F  181.0   68.0
68      F  178.0   66.0
69      M  166.0   70.0
70      M  179.0   67.0
72      F  175.0   68.0
73      F  168.0   70.0
75      M  181.0   73.0
76      M  175.0   69.0
77      M  173.0   67.0
78      M  173.0   64.0
79      F  175.0   68.0
81      F  177.0   70.0
82      F  177.0   71.0
83      F  178.0   67.0
84      F  176.0   66.0
85      M  170.0   72.0
86      F  171.0   73.0
88      F  170.0   70.0
89      F  186.0   72.0
91      F  180.0   65.0
92      M  186.0   73.0
95      F  171.0   72.0
96      F  176.0   67.0
97      M  173.0   68.0
98      F  179.0   69.0
99      F  174.0   66.0

[85 rows x 3 columns]

In [29]:
testDF=DF[~select] # 15개의 test data 뽑힘.
testDF

gender height weight
0       F  179.0   68.0
5       M  180.0   61.0
7       M  185.0   70.0
14      M  171.0   66.0
37      M  170.0   65.0
43      M  179.0   68.0
55      F  171.0   64.0
63      F  175.0   69.0
71      M  166.0   64.0
74      M  170.0   66.0
80      M  183.0   66.0
87      M  184.0   70.0
90      M  169.0   63.0
93      F  169.0   65.0
94      F  188.0   70.0

In [31]:
print(trainDF, "\n\n", testDF)

   gender height weight
1       F  180.0   71.0
2       F  166.0   67.0
3       M  173.0   73.0
4       F  187.0   66.0
6       F  174.0   66.0
8       F  177.0   67.0
9       F  175.0   67.0
10      F  172.0   64.0
11      M  175.0   66.0
12      F  178.0   68.0
13      M  184.0   67.0
15      F  171.0   69.0
16      M  171.0   74.0
17      F  177.0   68.0
18      M  177.0   70.0
19      F  161.0   67.0
20      F  178.0   64.0
21      M  189.0   65.0
22      F  177.0   66.0
23      F  176.0   70.0
24      F  169.0   69.0
25      F  181.0   67.0
26      M  182.0   64.0
27      F  186.0   69.0
28      M  172.0   68.0
29      M  189.0   72.0
30      F  177.0   71.0
31      M  176.0   67.0
32      F  163.0   70.0
33      F  185.0   67.0
..    ...    ...    ...
62      M  176.0   70.0
64      F  169.0   69.0
65      F  173.0   71.0
66      F  184.0   68.0
67      F  181.0   68.0
68      F  178.0   66.0
69      M  166.0   70.0
70      M  179.0   67.0
72      F  175.0   68.0
73      F  168.0

In [34]:
# 남녀성비를 대충 맞추고 싶으면 // 미리 성별로 나눠놓고 남자중 50프로, 여자중 50프로 뽑도록 하면된다.
x=np.random.rand(100)
gender=np.where(x>0.5,"M","F")
height=np.rint(np.random.normal(loc=175,scale=6,size=100))
weight=np.rint(np.random.normal(loc=68,scale=3,size=100))
# DF=DataFrame(np.array([gender,height,weight]).T,columns=["gender","height","weight"]) #array로 만들었기 때문에 다 문자로 바뀜!
DF=DataFrame({"gender":gender,"height":height,"weight":weight}) #그런거 대신 이렇게 만들어줘야

#이런 식으로 데이터가 있다고 가정
np.random.seed(12298) #없어도되는 코드. 그냥 편의상고정해놓음.
rand_num=np.random.rand(100) #0에서 1사이의 수 뽑음 
#90%는 train, 10%는 test뽑는다고 하면,
select=rand_num<0.9
np.sum(select) # 약 90프로가 속함.
select


male=DF[DF.gender=="M"]; female=DF[DF.gender=="F"]
NewData=DF[(DF.gender=="M")&(DF.height>=180)]
NewData

gender  height  weight
5       M   180.0    61.0
7       M   185.0    70.0
13      M   184.0    67.0
21      M   189.0    65.0
26      M   182.0    64.0
29      M   189.0    72.0
35      M   182.0    72.0
41      M   180.0    64.0
75      M   181.0    73.0
80      M   183.0    66.0
87      M   184.0    70.0
92      M   186.0    73.0

In [58]:
Ex1=Series(np.random.binomial(n=10,p=0.6,size=6),index=["A","B","D","E","F","H"])
Ex2=Series(np.random.binomial(n=50,p=0.4,size=6),index=["B","C","A","D","F","E"])
print(Ex1,"\n\n",Ex2,"\n\n",Ex1+Ex2,"\n") #그냥 산술연산자는 하나도 없으면 없게 뜸!

A    6
B    5
D    3
E    8
F    6
H    5
dtype: int32 

 B    18
C    15
A    17
D    14
F    21
E    20
dtype: int32 

 A    23.0
B    23.0
C     NaN
D    17.0
E    28.0
F    27.0
H     NaN
dtype: float64 



In [60]:
print(Ex1.add(Ex2)) # 옵션 안넣으면 그냥 산술자랑 동일

A    23.0
B    23.0
C     NaN
D    17.0
E    28.0
F    27.0
H     NaN
dtype: float64


In [59]:
print(Ex1.add(Ex2,fill_value=0)) # 옵션넣으면 없는값은0으로 채워넣어 더함

A    23.0
B    23.0
C    15.0
D    17.0
E    28.0
F    27.0
H     5.0
dtype: float64


In [68]:
Ex1=Series([3,5,1],index=["att","hw","etc"])
Ex2=Series([3,5,1],index=["st1","st4","st2"])
DF=DataFrame({"att":[5,7,8,6],"hw":[8,7,9,6],"mid":[36,32,25,28],"fin":[32,27,19,20]},index=["st1","st2","st3","st4"])
print(DF, "\n\n", Ex1, "\n\n", DF+Ex1) #더해줄 값 없으면 결측

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 

 att    3
hw     5
etc    1
dtype: int64 

       att  etc  fin    hw  mid
st1   8.0  NaN  NaN  13.0  NaN
st2  10.0  NaN  NaN  12.0  NaN
st3  11.0  NaN  NaN  14.0  NaN
st4   9.0  NaN  NaN  11.0  NaN


In [70]:
DF.add(Ex1) # default : 열 인덱스

att  etc  fin    hw  mid
st1   8.0  NaN  NaN  13.0  NaN
st2  10.0  NaN  NaN  12.0  NaN
st3  11.0  NaN  NaN  14.0  NaN
st4   9.0  NaN  NaN  11.0  NaN

In [72]:
DF.add(Ex1,axis=0) # default : 행 인덱스

att  hw  mid  fin
att  NaN NaN  NaN  NaN
etc  NaN NaN  NaN  NaN
hw   NaN NaN  NaN  NaN
st1  NaN NaN  NaN  NaN
st2  NaN NaN  NaN  NaN
st3  NaN NaN  NaN  NaN
st4  NaN NaN  NaN  NaN

In [73]:
DF.add(Ex2,axis=0)

att    hw   mid   fin
st1   8.0  11.0  39.0  35.0
st2   8.0   8.0  33.0  28.0
st3   NaN   NaN   NaN   NaN
st4  11.0  11.0  33.0  25.0

In [76]:
print(np.exp(Ex1), "\n\n", np.sqrt(Ex1)) # 시리즈의 원소별 지수값, 제곱근값

att     20.085537
hw     148.413159
etc      2.718282
dtype: float64 

 att    1.732051
hw     2.236068
etc    1.000000
dtype: float64


In [77]:
Ex1=Series([3,5,1],index=["att","hw","etc"])
Ex2=Series([4,2,10],index=["st1","st4","st2"])
print(np.minimum(Ex1,Ex2)) # numpy에서는 자리(들어가있는 순서)로 계산. index를 전혀고려하지 않음. 고로 크기도 똑같아야함!
# numpy함수를 쓰려면, 인덱스를 보지 않고 그냥 배열로 생각하고 계산해야함!

att    3
hw     2
etc    1
dtype: int64


In [79]:
DF=DataFrame({"att":[5,7,8,6],"hw":[8,7,9,6],"mid":[36,32,25,28],"fin":[32,27,19,20]},index=["st1","st2","st3","st4"])
print(DF, "\n\n", DF.apply(np.sum)) #numpy 함수이용해서 구하기 열별로 계산.

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 

 att     26
hw      30
mid    121
fin     98
dtype: int64


In [81]:
print(DF, "\n\n", DF.apply(np.sum, axis=1)) # 행별 계산

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 

 st1    81
st2    73
st3    61
st4    60
dtype: int64


In [83]:
def f(x):
    return(Series([x.min(),x.max(),x.max()-x.min()],index=["최소","최대","범위"]))
print(DF,"\n\n",DF.apply(f)) #default가 열계산이므로 축바꾸지 않음
DF.apply(f) #시리즈 4개를 받아 데이터프레임처럼 보여줌

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 

     att  hw  mid  fin
최소    5   6   25   19
최대    8   9   36   32
범위    3   3   11   13


att  hw  mid  fin
최소    5   6   25   19
최대    8   9   36   32
범위    3   3   11   13

In [84]:
print(DF,"\n\n",DF.apply(f,axis=1)) #행계산
DF.apply(f) #시리즈 4개를 받아 데이터프레임처럼 보여줌

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 

      최소  최대  범위
st1   5  36  31
st2   7  32  25
st3   8  25  17
st4   6  28  22


att  hw  mid  fin
최소    5   6   25   19
최대    8   9   36   32
범위    3   3   11   13

In [85]:
print(DF, "\n\n", DF.applymap(np.exp))
np.exp(DF) # 두개 다 동

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 

              att           hw           mid           fin
st1   148.413159  2980.957987  4.311232e+15  7.896296e+13
st2  1096.633158  1096.633158  7.896296e+13  5.320482e+11
st3  2980.957987  8103.083928  7.200490e+10  1.784823e+08
st4   403.428793   403.428793  1.446257e+12  4.851652e+08


att           hw           mid           fin
st1   148.413159  2980.957987  4.311232e+15  7.896296e+13
st2  1096.633158  1096.633158  7.896296e+13  5.320482e+11
st3  2980.957987  8103.083928  7.200490e+10  1.784823e+08
st4   403.428793   403.428793  1.446257e+12  4.851652e+08

In [90]:
Ex1=Series([3,5,np.inf,7,5,np.nan,6,1],index=["a3","a2","a1","a8","a6","a4","a7","a5"])
DF=DataFrame({"att":[5,7,8,6],"hw":[8,7,9,6],"mid":[36,32,25,28],"fin":[32,27,19,20]},index=["st1","st2","st3","st4"])
print(Ex1,"\n\n",Ex1.sort_index(),"\n\n",Ex1.sort_index(ascending=False)) # 오름차순, 내림차순 # 인덱스와 values는 함께 움직임

a3    3.0
a2    5.0
a1    inf
a8    7.0
a6    5.0
a4    NaN
a7    6.0
a5    1.0
dtype: float64 

 a1    inf
a2    5.0
a3    3.0
a4    NaN
a5    1.0
a6    5.0
a7    6.0
a8    7.0
dtype: float64 

 a8    7.0
a7    6.0
a6    5.0
a5    1.0
a4    NaN
a3    3.0
a2    5.0
a1    inf
dtype: float64


In [92]:
print(Ex1,"\n\n",Ex1.sort_values(),"\n\n",Ex1.sort_values(ascending=False)) #값으로 정렬 오름차순기준 #내림차순

a3    3.0
a2    5.0
a1    inf
a8    7.0
a6    5.0
a4    NaN
a7    6.0
a5    1.0
dtype: float64 

 a5    1.0
a3    3.0
a2    5.0
a6    5.0
a7    6.0
a8    7.0
a1    inf
a4    NaN
dtype: float64 

 a1    inf
a8    7.0
a7    6.0
a6    5.0
a2    5.0
a3    3.0
a5    1.0
a4    NaN
dtype: float64


In [94]:
print(DF,"\n\n",DF.sort_index(),"\n\n",DF.sort_index(ascending=False,axis=1)) # 축=1 -> 열이 함께 움직임

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 

      att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 

      mid  hw  fin  att
st1   36   8   32    5
st2   32   7   27    7
st3   25   9   19    8
st4   28   6   20    6


In [96]:
print(DF,"\n\n",DF.sort_values(by="fin"),"\n\n",DF.sort_values(ascending=False,by="fin")) #by : 어떤 인덱스를 기준으로 할건지 정해

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 

      att  hw  mid  fin
st3    8   9   25   19
st4    6   6   28   20
st2    7   7   32   27
st1    5   8   36   32 

      att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st4    6   6   28   20
st3    8   9   25   19


In [100]:
#동률인 경우 기준을 여러개로 잡는 경우가 있음
DF=DataFrame({"att":[5,7,8,6,7],"hw":[8,7,9,6,6],"mid":[36,32,25,28,22],"fin":[32,27,19,20,27]},index=["st1","st2","st3","st4","st5"])
print(DF,"\n\n",DF.sort_values(by="fin"),"\n")#동률이라 입력된 순서대로 동률 처리
print(DF.sort_values(by=["fin","mid"])) #fin에서 동률인건 mid로 다시 정

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20
st5    7   6   22   27 

      att  hw  mid  fin
st3    8   9   25   19
st4    6   6   28   20
st2    7   7   32   27
st5    7   6   22   27
st1    5   8   36   32 

     att  hw  mid  fin
st3    8   9   25   19
st4    6   6   28   20
st5    7   6   22   27
st2    7   7   32   27
st1    5   8   36   32


In [102]:
print(Ex1, "\n\n",Ex1.rank()) # 순위값 #작은게 1

a3    3.0
a2    5.0
a1    inf
a8    7.0
a6    5.0
a4    NaN
a7    6.0
a5    1.0
dtype: float64 

 a3    2.0
a2    3.5
a1    7.0
a8    6.0
a6    3.5
a4    NaN
a7    5.0
a5    1.0
dtype: float64


In [104]:
print(Ex1, "\n\n",Ex1.rank(method="min")) 

a3    3.0
a2    5.0
a1    inf
a8    7.0
a6    5.0
a4    NaN
a7    6.0
a5    1.0
dtype: float64 

 a3    2.0
a2    3.0
a1    7.0
a8    6.0
a6    3.0
a4    NaN
a7    5.0
a5    1.0
dtype: float64


In [105]:
print(Ex1, "\n\n",Ex1.rank(method="first")) # 들어간 순서대로

a3    3.0
a2    5.0
a1    inf
a8    7.0
a6    5.0
a4    NaN
a7    6.0
a5    1.0
dtype: float64 

 a3    2.0
a2    3.0
a1    7.0
a8    6.0
a6    4.0
a4    NaN
a7    5.0
a5    1.0
dtype: float64


In [106]:
print(DF, "\n\n",DF.rank(method="average")) 

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20
st5    7   6   22   27 

      att   hw  mid  fin
st1  1.0  4.0  5.0  5.0
st2  3.5  3.0  4.0  3.5
st3  5.0  5.0  2.0  1.0
st4  2.0  1.5  3.0  2.0
st5  3.5  1.5  1.0  3.5


In [107]:
print(DF, "\n\n",DF.rank(axis=1,method="average"))  #행별 순위계산

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20
st5    7   6   22   27 

      att   hw  mid  fin
st1  1.0  2.0  4.0  3.0
st2  1.5  1.5  4.0  3.0
st3  1.0  2.0  4.0  3.0
st4  1.5  1.5  4.0  3.0
st5  2.0  1.0  3.0  4.0


In [109]:
print(Ex1.index.is_unique,"\n",DF) #괄호없이 사용 #중복색인있는지 확

True 
      att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20
st5    7   6   22   27


In [110]:
Ex1.mean() # 무한대 포함 -> 무한대값이 나옴

inf

In [111]:
Ex1.mean(skipna=False) # 결측값을 무시하지 않음 (EX1이 결측이 있으므로 결과는 nan)

nan

In [112]:
Ex1=Series([3,5,9,7,5,np.nan,6,1],index=["a3","a2","a1","a8","a6","a4","a7","a5"])
Ex1.mean() # default : NA skip

5.142857142857143

In [115]:
print(DF, "\n\n", DF.mean()) # 각 변수별 평균

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20
st5    7   6   22   27 

 att     6.6
hw      7.2
mid    28.6
fin    25.0
dtype: float64


In [117]:
DF=DataFrame({"att":[5,7,8,6,7],"hw":[8,7,9,np.nan,6],
              "mid":[36,32,25,28,22],"fin":[32,27,np.nan,20,27]},index=["st1","st2","st3","st4","st5"])
print(DF)
DF.mean()

     att   hw  mid   fin
st1    5  8.0   36  32.0
st2    7  7.0   32  27.0
st3    8  9.0   25   NaN
st4    6  NaN   28  20.0
st5    7  6.0   22  27.0


att     6.6
hw      7.5
mid    28.6
fin    26.5
dtype: float64

In [118]:
DF.mean(skipna=False) 

att     6.6
hw      NaN
mid    28.6
fin     NaN
dtype: float64

In [120]:
print(DF)
DF.mean(axis=1) # 행평균 

     att   hw  mid   fin
st1    5  8.0   36  32.0
st2    7  7.0   32  27.0
st3    8  9.0   25   NaN
st4    6  NaN   28  20.0
st5    7  6.0   22  27.0


st1    20.25
st2    18.25
st3    14.00
st4    18.00
st5    15.50
dtype: float64

In [121]:
print(DF)
DF.cumsum() # 누적합 #NA있는부분은 NA. 그이후에는 NA를 뛰어넘음

     att   hw  mid   fin
st1    5  8.0   36  32.0
st2    7  7.0   32  27.0
st3    8  9.0   25   NaN
st4    6  NaN   28  20.0
st5    7  6.0   22  27.0


att    hw    mid    fin
st1   5.0   8.0   36.0   32.0
st2  12.0  15.0   68.0   59.0
st3  20.0  24.0   93.0    NaN
st4  26.0   NaN  121.0   79.0
st5  33.0  30.0  143.0  106.0

In [122]:
print(DF)
DF.cumsum(skipna=False) # 누적합 #NA값이 나오면서부터 결측`

     att   hw  mid   fin
st1    5  8.0   36  32.0
st2    7  7.0   32  27.0
st3    8  9.0   25   NaN
st4    6  NaN   28  20.0
st5    7  6.0   22  27.0


att    hw    mid   fin
st1   5.0   8.0   36.0  32.0
st2  12.0  15.0   68.0  59.0
st3  20.0  24.0   93.0   NaN
st4  26.0   NaN  121.0   NaN
st5  33.0   NaN  143.0   NaN

In [123]:
print(DF)
DF.quantile(q=[0.15,0.95]) #15퍼센트분위수, 95퍼센트분위수=상위5프로`

     att   hw  mid   fin
st1    5  8.0   36  32.0
st2    7  7.0   32  27.0
st3    8  9.0   25   NaN
st4    6  NaN   28  20.0
st5    7  6.0   22  27.0


att    hw   mid    fin
0.15  5.6  6.45  23.8  23.15
0.95  7.8  8.85  35.2  31.25

In [124]:
print(DF)
DF.diff() #1차차분` 자기자신과 자기전거를 뺌`

     att   hw  mid   fin
st1    5  8.0   36  32.0
st2    7  7.0   32  27.0
st3    8  9.0   25   NaN
st4    6  NaN   28  20.0
st5    7  6.0   22  27.0


att   hw  mid  fin
st1  NaN  NaN  NaN  NaN
st2  2.0 -1.0 -4.0 -5.0
st3  1.0  2.0 -7.0  NaN
st4 -2.0  NaN  3.0  NaN
st5  1.0  NaN -6.0  7.0

In [125]:
print(DF)
DF.describe() #기술통계랑`

     att   hw  mid   fin
st1    5  8.0   36  32.0
st2    7  7.0   32  27.0
st3    8  9.0   25   NaN
st4    6  NaN   28  20.0
st5    7  6.0   22  27.0


att        hw        mid        fin
count  5.000000  4.000000   5.000000   4.000000
mean   6.600000  7.500000  28.600000  26.500000
std    1.140175  1.290994   5.549775   4.932883
min    5.000000  6.000000  22.000000  20.000000
25%    6.000000  6.750000  25.000000  25.250000
50%    7.000000  7.500000  28.000000  27.000000
75%    7.000000  8.250000  32.000000  28.250000
max    8.000000  9.000000  36.000000  32.000000

In [126]:
x=np.random.rand(100)
gender=np.where(x>0.5,"M","F")
height=np.rint(np.random.normal(loc=175,scale=6,size=100))
weight=np.rint(np.random.normal(loc=68,scale=3,size=100))
# DF=DataFrame(np.array([gender,height,weight]).T,columns=["gender","height","weight"]) #array로 만들었기 때문에 다 문자로 바뀜!
DF=DataFrame({"gender":gender,"height":height,"weight":weight}) #그런거 대신 이렇게 만들어줘야
DF.gender.describe() #문자는 count가 갯수. 

count     100
unique      2
top         F
freq       57
Name: gender, dtype: object